# Generated by Django 3.2 on 2024-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20240815_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tsv_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tsv_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
